var i=Object.defineProperty;var m=Object.getOwnPropertyDescriptor;var g=Object.getOwnPropertyNames;var h=Object.prototype.hasOwnProperty;var F=(s,e)=>{for(var t in e)i(s,t,{get:e[t],enumerable:!0})},f=(s,e,t,a)=>{if(e&&typeof e=="object"||typeof e=="function")for(let r of g(e))!h.call(s,r)&&r!==t&&i(s,r,{get:()=>e[r],enumerable:!(a=m(e,r))||a.enumerable});return s};var T=s=>f(i({},"__esModule",{value:!0}),s);var v={};F(v,{default:()=>l});module.exports=T(v);var n=require("obsidian"),p=`---
created: {{date}}
updated: {{date}}
type: inbox
status: unprocessed
source: manual
processed: false
tags: []
---`,o={defaultFrontmatterTemplate:p,dateFormat:"YYYY-MM-DD",preventDuplicateFrontmatter:!0,enableExcludedFolders:!1,excludedFolders:[]},u="frontmatter-button-file-plus",w=`
<g fill="none" stroke="currentColor" stroke-width="8" stroke-linecap="round" stroke-linejoin="round">
	<path d="M58 8H25a8 8 0 0 0-8 8v67a8 8 0 0 0 8 8h50a8 8 0 0 0 8-8V33z" />
	<path d="M58 8v25h25" />
	<path d="M50 50v25" />
	<path d="M38 63h25" />
</g>`,l=class extends n.Plugin{async onload(){await this.loadSettings(),(0,n.addIcon)(u,w),this.addCommand({id:"add-default-frontmatter",name:"Add default frontmatter to current note",icon:u,callback:()=>{this.addDefaultFrontmatterToCurrentNote()}}),this.addSettingTab(new d(this.app,this))}async loadSettings(){let e=await this.loadData(),t=Object.assign({},o,e);this.settings={defaultFrontmatterTemplate:typeof t.defaultFrontmatterTemplate=="string"?t.defaultFrontmatterTemplate:o.defaultFrontmatterTemplate,dateFormat:typeof t.dateFormat=="string"&&t.dateFormat.trim().length>0?t.dateFormat:o.dateFormat,preventDuplicateFrontmatter:typeof t.preventDuplicateFrontmatter=="boolean"?t.preventDuplicateFrontmatter:o.preventDuplicateFrontmatter,enableExcludedFolders:typeof t.enableExcludedFolders=="boolean"?t.enableExcludedFolders:o.enableExcludedFolders,excludedFolders:Array.isArray(t.excludedFolders)?t.excludedFolders.filter(a=>typeof a=="string"):o.excludedFolders}}async saveSettings(){await this.saveData(this.settings)}async addDefaultFrontmatterToCurrentNote(){try{let e=this.app.workspace.getActiveFile();if(!this.isMarkdownFile(e)){new n.Notice("No active Markdown file.");return}if(this.isInExcludedFolder(e)){new n.Notice("Folder is excluded from frontmatter updates.");return}let t=await this.app.vault.read(e);if(this.startsWithYamlFrontmatter(t)){new n.Notice("Note already has frontmatter.");return}let a=this.renderTemplate(e);if(!this.startsWithYamlFrontmatter(a)){new n.Notice("Error adding frontmatter.");return}let r=t.length>0&&!a.endsWith(`
`)?`
`:"",c=`${a}${r}${t}`;await this.app.vault.modify(e,c),new n.Notice("Frontmatter added successfully.")}catch(e){console.error("Error adding frontmatter",e),new n.Notice("Error adding frontmatter.")}}isMarkdownFile(e){return e instanceof n.TFile&&e.extension.toLowerCase()==="md"}startsWithYamlFrontmatter(e){return/^---\r?\n[\s\S]*?\r?\n---(?:\r?\n|$)/.test(e)}isInExcludedFolder(e){return this.settings.enableExcludedFolders?this.settings.excludedFolders.some(t=>{let a=this.normalizeFolderPath(t);return a.length>0&&(e.path===a||e.path.startsWith(`${a}/`))}):!1}normalizeFolderPath(e){return e.trim().replace(/^\/+|\/+$/g,"")}renderTemplate(e){let t=(0,n.moment)(),a=e.basename;return this.settings.defaultFrontmatterTemplate.replace(/{{date}}/g,t.format(this.settings.dateFormat||"YYYY-MM-DD")).replace(/{{title}}/g,a).replace(/{{time}}/g,t.format("HH:mm"))}},d=class extends n.PluginSettingTab{constructor(e,t){super(e,t),this.plugin=t}display(){let{containerEl:e}=this;e.empty(),e.createEl("h2",{text:"Frontmatter Button"}),new n.Setting(e).setName("Default frontmatter template").setDesc("YAML frontmatter to prepend when the command runs.").addTextArea(t=>{t.setPlaceholder(p).setValue(this.plugin.settings.defaultFrontmatterTemplate).onChange(async a=>{this.plugin.settings.defaultFrontmatterTemplate=a,await this.plugin.saveSettings()}),t.inputEl.rows=10,t.inputEl.cols=40}),new n.Setting(e).setName("Date format").setDesc("Format used for {{date}}.").addText(t=>t.setPlaceholder("YYYY-MM-DD").setValue(this.plugin.settings.dateFormat).onChange(async a=>{this.plugin.settings.dateFormat=a.trim()||"YYYY-MM-DD",await this.plugin.saveSettings()})),new n.Setting(e).setName("Prevent duplicate frontmatter").setDesc("Do nothing when the note already starts with YAML frontmatter.").addToggle(t=>t.setValue(this.plugin.settings.preventDuplicateFrontmatter).onChange(async a=>{this.plugin.settings.preventDuplicateFrontmatter=a,await this.plugin.saveSettings()})),new n.Setting(e).setName("Enable excluded folders").setDesc("Skip notes inside the folders listed below.").addToggle(t=>t.setValue(this.plugin.settings.enableExcludedFolders).onChange(async a=>{this.plugin.settings.enableExcludedFolders=a,await this.plugin.saveSettings()})),new n.Setting(e).setName("Excluded folders").setDesc("One folder path per line, relative to the vault root.").addTextArea(t=>{t.setPlaceholder(`Templates
Archive`).setValue(this.plugin.settings.excludedFolders.join(`
`)).onChange(async a=>{this.plugin.settings.excludedFolders=a.split(`
`).map(r=>r.trim()).filter(r=>r.length>0),await this.plugin.saveSettings()}),t.inputEl.rows=5,t.inputEl.cols=40})}};
